applications:
- application_name: sffda
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://public-firing-range.appspot.com
  type: web
aws:
- account_id: '859000334327'
  regions:
  - us-east-1
  type: account
deployment:
  environments:
  - staging
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - sffda
      tags:
      - staging
      trigger: deployment
