applications:
- application_name: sffd.dsad
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://public-firing-range.appspot.com
  type: web
deployment:
  environments:
  - staging
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - sffd.dsad
      tags:
      - staging
      trigger: deployment
