applications:
- application_name: sffda
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://public-firing-range.appspot.com
  type: web
aws:
- account_id: '859000334327'
  regions:
  - us-east-2
  - us-west-1
  - af-south-1
  - us-east-1
  - us-west-2
  - ap-east-1
  - ap-southeast-3
  - ap-south-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-south-1
  - eu-west-3
  - eu-north-1
  - me-south-1
  - sa-east-1
  - us-gov-east-1
  type: account
deployment:
  environments:
  - staging
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - sffda
      tags:
      - staging
      trigger: deployment
