applications:
- api_domain: cddswde.dewdew.dewdew
  application_name: sffdaaaaaaa
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://public-firing-range.appspot.com
  type: web
deployment:
  environments:
  - staging
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - sffdaaaaaaa
      tags:
      - staging
      trigger: deployment
